# Generated by Django 5.2.18 on 2026-10-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data do jantar')),
                ('descricao', models.TextField(help_text='Prato principal, acompanhamentos, sobremesa…', verbose_name='Cardápio')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cardápio',
                'verbose_name_plural': 'cardápios',
                'ordering': ['-data'],
            },
        ),
    ]
