# Generated by Django 5.2.18 on 2026-10-06 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_vinculo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de vínculo',
                'verbose_name_plural': 'códigos de vínculo',
            },
        ),
    ]
